### ISSUE TITLE
Optiburb incompatible with osmnx 0.16

### ISSUE THREAD

**Issue by rgmerk** [jgc234/optiburb#12]
Hi, 

it appears that optiburb is incompatible with osmnx 0.16.

I'd submit a patch if it was obvious what the correct replacement API call is, but it's not straightforward.  

Reading the documentation, it seems that the correct way to do this in newer versions is  to retrieve a graph and them convert to a gdf, as shown in the example here:

https://github.com/gboeing/osmnx-examples/blob/master/notebooks/02-routing-speed-time.ipynb

Unfortunately, I'm not sure exactly how you're using the gdf so I'm not sure on the exact values for all of the arguments.

Cheers,
Robert.

```
xubuntu@xubuntu-VirtualBox:~/src/optiburb$ pip3 freeze | grep osmnx
osmnx==0.16.0
xubuntu@xubuntu-VirtualBox:~/src/optiburb$ ./optiburb.py "brunswick, victoria, australia"
2020-10-02 14:03:06 Configured osmnx
2020-10-02 14:03:06 optiburb.py:__init__:86 [WARNING] WARNING - this program does not consider the direction of one-way roads or other roads that may be not suitable for your mode of transport. You must confirm the path safe for yourself
2020-10-02 14:03:06 optiburb.py:get_osm_polygon:113 [INFO] searching for query=brunswick, victoria, australia, which_result=1
Traceback (most recent call last):
  File "./optiburb.py", line 738, in <module>
    polygon = burbing.get_osm_polygon(name, args.select, args.buffer)
  File "./optiburb.py", line 115, in get_osm_polygon
    gdf = osmnx.gdf_from_place(name, buffer_dist=buffer_dist, which_result=select)
AttributeError: module 'osmnx' has no attribute 'gdf_from_place'
```

**Comment by jskinner** [comment]
FWIW, it appears to work for me if I replace `osmnx.gdf_from_place` with `osmnx.geocode_to_gdf`
