### ISSUE TITLE
Optiburb Radius failing

### ISSUE THREAD

**Issue by Egosumumbravir** [jgc234/optiburb#13]
Windows environment, python-3.8.10-amd64, dependencies sorted.

I can generate a GPX of my suburb.  With new restrictions, I wanted to generate a GPX of everything within 2.5km.

> optiburb.py --debug=debug --save-fig --save-boundary --start "My Address, Suburb, South Australia, Australia" --buffer 2499 "My Address, Suburb, South Australia, Australia"
> 2021-07-21 10:39:05 optiburb.py:<module>:709 [DEBUG] called with args - Namespace(buffer=2499, debug='debug', feature_deadend=False, names=['My Address, Suburb, South Australia, Australia'], prune=False, save_boundary=True, save_fig=True, select=1, shapefile=None, simplify=False, simplify_gpx=True, start='My Address, Suburb, South Australia, Australia')
> 2021-07-21 10:39:05 optiburb.py:__init__:74 [DEBUG] custom_filter=["highway"]["area"!~"yes"]["highway"!~"motorway|motorway_link|bridleway|footway|service|pedestrian|steps|stairs|escalator|elevator|construction|proposed|demolished|escape|bus_guideway|sidewalk|crossing|bus_stop|traffic_signals|stop|give_way|milestone|platform|speed_camera|raceway|rest_area|traffic_island|services|yes|no|drain|street_lamp|razed|corridor|abandoned"]["access"!~"private|no|customers"]["bicycle"!~"dismount|use_sidepath|private|no"]["service"!~"private|parking_aisle"]["motorroad"!="yes"]["golf_cart"!~"yes|designated|private"][!"waterway"][!"razed"]
> 2021-07-21 10:39:05 Configured OSMnx 1.1.1
> 2021-07-21 10:39:05 HTTP response caching is on
> 2021-07-21 10:39:05 optiburb.py:__init__:86 [WARNING] WARNING - this program does not consider the direction of one-way roads or other roads that may be not suitable for your mode of transport. You must confirm the path safe for yourself
> 2021-07-21 10:39:05 optiburb.py:get_osm_polygon:113 [INFO] searching for query=My Address, Suburb, South Australia, Australia, which_result=1
> 2021-07-21 10:39:05 Retrieved response from cache file "cache\b80f0950a39548b054c3d7acd643b0291f2ba8c6.json"
> 2021-07-21 10:39:05 Nominatim geocoder returned a LineString as the geometry for query "My Address, Suburb, South Australia, Australia"
> 2021-07-21 10:39:05 Projected GeoDataFrame to +proj=utm +zone=54 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
> 2021-07-21 10:39:05 Projected GeoDataFrame to epsg:4326
> 2021-07-21 10:39:05 Buffered GeoDataFrame to 2499 meters
> 2021-07-21 10:39:05 Created GeoDataFrame with 1 rows from 1 queries
> 2021-07-21 10:39:05 optiburb.py:get_osm_polygon:116 [INFO] gdf=                                            geometry  bbox_north  bbox_south  ...    class         type  importance
> 0  POLYGON ((138.71772 -34.77658, 138.72113 -34.7...   -34.79887  -34.799054  ...  highway  residential        1.64
> 
> [1 rows x 14 columns]
> 2021-07-21 10:39:05 optiburb.py:create_gpx_polygon:574 [INFO] saving suburb boundary - burb_polygon_1_my_address_south_australia_australia.gpx
> Traceback (most recent call last):
>   File "D:\optiburb-master2\optiburb.py", line 748, in <module>
>     burbing.set_start_location(args.start)
>   File "D:\optiburb-master2\optiburb.py", line 142, in set_start_location
>     point =  osmnx.utils_geo.geocode(addr)
> AttributeError: module 'osmnx.utils_geo' has no attribute 'geocode'

Searching for "My Address, Suburb, South Australia, Australia" directly on OSM delivers my street, but no resolution of the numbers within.  Is that the issue here or am I missing something vital?

**Comment by Egosumumbravir** [comment]
Might have solved it - https://github.com/gboeing/osmnx/blob/main/CHANGELOG.md

"0.16.0 (2020-09-07)
    remove deprecated utils_geo.geocode function (replaced by geocoder.geocode function in v0.15.0)
"
Passed it's normal fault point and currently generating the GPX.  Fingers crossed.

**Comment by Egosumumbravir** [comment]
Bah, failed again.  Different point at least.
Working the problems
**Error #1:** File "D:\optiburb-master2\optiburb.py", line 142, in set_start_location
point = osmnx.utils_geo.geocode(addr)
AttributeError: module 'osmnx.utils_geo' has no attribute 'geocode

LINE142: point =  osmnx.utils_geo.geocode(addr)
FIX: point =  osmnx.geocoder.geocode(addr)


**Error #2:** UserWarning: The `get_nearest_node` function has been deprecated and will be removed in a future release. Use the more efficient `distance.nearest_nodes` instead.

LINE 414: (start_node, distance) = osmnx.distance.get_nearest_node(g, start_addr, return_dist=True)
FIX: (start_node, distance) = osmnx.distance.nearest_nodes(g, start_addr, return_dist=True)

**Error #3:** Created nodes GeoDataFrame from graph
Traceback (most recent call last):
  File "D:\optiburb-master3\optiburb2.py", line 769, in <module>
    burbing.determine_circuit()
  File "D:\optiburb-master3\optiburb2.py", line 371, in determine_circuit
    start_node = self.get_start_node(self.g, self.start)
  File "D:\optiburb-master3\optiburb2.py", line 414, in get_start_node
    (start_node, distance) = osmnx.distance.get_nearest_node(g, start_addr, return_dist=True)
  File "C:\Users\Aetherone\AppData\Local\Programs\Python\Python38\lib\site-packages\osmnx\distance.py", line 357, in get_nearest_node
    nn, dist = nearest_nodes(G, X=[point[1]], Y=[point[0]], return_dist=True)
  File "C:\Users\Aetherone\AppData\Local\Programs\Python\Python38\lib\site-packages\osmnx\distance.py", line 200, in nearest_nodes
    raise ImportError("scikit-learn must be installed to search an unprojected graph")
ImportError: scikit-learn must be installed to search an unprojected graph

FIX: pip install scikit-learn

Now we get output.  Testing with a small radius - 500 meters generates an oval?

**Comment by Egosumumbravir** [comment]
Scratch error #2 - replacing osmnx.distance.get_nearest_node(addr) with osmnx.geocoder.geocode(addr) gives error

File "D:\optiburb-master3\optiburb3.py", line 414, in get_start_node
    (start_node, distance) = osmnx.distance.nearest_nodes(g, start_addr, return_dist=True)
TypeError: nearest_nodes() missing 1 required positional argument: 'Y'

Leaving osmnx.utils_geo.geocode(addr) as osmnx.utils_geo.geocode(addr) works for now, but will be broken at some point.

**Comment by Egosumumbravir** [comment]
At a guess, I'm getting an oval because OSM can't resolve points - it's drawing around the LINE that OSM says is my street.
