### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by bj793** [jgc234/optiburb#2]
Hi. Great script idea. Thank you! Getting "Multiploygon' object has no attribute 'exterior' when trying to run script. Tried a number of different suburbs but same error. 

2020-07-30 10:28:50 optiburb.py:create_gpx_polygon:484 [INFO] saving suburb boundary - burb_polygon_'richmond__victoria__australia'.gpx
Traceback (most recent call last):
  File "optiburb.py", line 668, in <module>
    burbing.create_gpx_polygon(burbing.region)
  File "optiburb.py", line 501, in create_gpx_polygon
    for x, y in polygon.exterior.coords:
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

----------------------------------------------------------------------
C:\burbing>python optiburb.py --simplify --simplify-gpx --prune --debug debug 'richmond, victoria, australia'
2020-07-30 10:28:46 optiburb.py:<module>:635 [DEBUG] called with args - Namespace(buffer=20, debug='debug', names=["'richmond,", 'victoria,', "australia'"], prune=True, save_boundary='False', save_fig='False', select=1, shapefile=None, simplify=True, simplify_gpx=True, start=None)
2020-07-30 10:28:46 Configured osmnx
2020-07-30 10:28:46 optiburb.py:__init__:64 [WARNING] WARNING - this program does not consider the direction of one-way roads or other roads that may be not suitable for your mode of transport. You must confirm the path safe for yourself
2020-07-30 10:28:46 optiburb.py:get_osm_polygon:91 [INFO] searching for query='richmond,, which_result=1
C:\Program Files (x86)\Python38-32\lib\site-packages\osmnx\boundaries.py:36: UserWarning: The `boundaries` module has been deprecated and will be removed in a future relase. Use the `geocoder` module's `geocode_to_gdf` function instead.
  warnings.warn(msg)
2020-07-30 10:28:46 Pausing 1 seconds before making HTTP GET request
2020-07-30 10:28:47 Get https://nominatim.openstreetmap.org/search?format=json&limit=1&dedupe=0&polygon_geojson=1&q=%27richmond%2C with timeout=180
2020-07-30 10:28:47 connectionpool.py:_new_conn:939 [DEBUG] Starting new HTTPS connection (1): nominatim.openstreetmap.org:443
2020-07-30 10:28:48 connectionpool.py:_make_request:433 [DEBUG] https://nominatim.openstreetmap.org:443 "GET /search?format=json&limit=1&dedupe=0&polygon_geojson=1&q=%27richmond%2C HTTP/1.1" 200 None
2020-07-30 10:28:48 Downloaded 0.5KB from nominatim.openstreetmap.org
2020-07-30 10:28:48 Saved response to cache file "cache\deb138ffe550bb73362d070e245d89dd.json"
2020-07-30 10:28:48 OSM returned a Point as the geometry
2020-07-30 10:28:49 Projected GeoDataFrame to +proj=utm +zone=18 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
2020-07-30 10:28:49 Projected GeoDataFrame to epsg:4326
2020-07-30 10:28:49 Buffered GeoDataFrame to 20 meters
2020-07-30 10:28:49 Created GeoDataFrame with 1 row for query "'richmond,"
2020-07-30 10:28:49 optiburb.py:get_osm_polygon:94 [INFO] gdf=                                            geometry                                         place_name  bbox_north  bbox_south  bbox_east  bbox_west
0  POLYGON ((-77.43405 37.53851, -77.43405 37.538...  Richmond, Richmond City, Virginia, 23298, Unit...   37.698509   37.378509  -77.27428  -77.59428
2020-07-30 10:28:49 optiburb.py:get_osm_polygon:91 [INFO] searching for query=victoria,, which_result=1
C:\Program Files (x86)\Python38-32\lib\site-packages\osmnx\boundaries.py:36: UserWarning: The `boundaries` module has been deprecated and will be removed in a future relase. Use the `geocoder` module's `geocode_to_gdf` function instead.
  warnings.warn(msg)
2020-07-30 10:28:49 Retrieved response from cache file "cache\e313c914b63ec1985c5792fcd8c3bf6d.json"
2020-07-30 10:28:49 Projected GeoDataFrame to +proj=utm +zone=55 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
2020-07-30 10:28:49 Projected GeoDataFrame to epsg:4326
2020-07-30 10:28:49 Buffered GeoDataFrame to 20 meters
2020-07-30 10:28:49 Created GeoDataFrame with 1 row for query "victoria,"
2020-07-30 10:28:49 optiburb.py:get_osm_polygon:94 [INFO] gdf=                                            geometry           place_name  bbox_north  bbox_south   bbox_east   bbox_west
0  MULTIPOLYGON (((140.96341 -34.39740, 140.96316...  Victoria, Australia  -33.980797  -39.198487  150.033282  140.961902
2020-07-30 10:28:50 optiburb.py:get_osm_polygon:91 [INFO] searching for query=australia', which_result=1
C:\Program Files (x86)\Python38-32\lib\site-packages\osmnx\boundaries.py:36: UserWarning: The `boundaries` module has been deprecated and will be removed in a future relase. Use the `geocoder` module's `geocode_to_gdf` function instead.
  warnings.warn(msg)
2020-07-30 10:28:50 Retrieved response from cache file "cache\e964202fa396a56531d954d158b3cfaa.json"
2020-07-30 10:28:50 Projected GeoDataFrame to +proj=utm +zone=53 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
2020-07-30 10:28:50 Projected GeoDataFrame to epsg:4326
2020-07-30 10:28:50 Buffered GeoDataFrame to 20 meters
2020-07-30 10:28:50 Created GeoDataFrame with 1 row for query "australia'"
2020-07-30 10:28:50 optiburb.py:get_osm_polygon:94 [INFO] gdf=                                            geometry place_name  bbox_north  bbox_south   bbox_east  bbox_west
0  MULTIPOLYGON (((167.68549 -29.00923, 167.68579...  Australia   -9.088012  -55.322817  168.226126  72.246193
2020-07-30 10:28:50 optiburb.py:create_gpx_polygon:484 [INFO] saving suburb boundary - burb_polygon_'richmond__victoria__australia'.gpx
Traceback (most recent call last):
  File "optiburb.py", line 668, in <module>
    burbing.create_gpx_polygon(burbing.region)
  File "optiburb.py", line 501, in create_gpx_polygon
    for x, y in polygon.exterior.coords:
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by jgc234** [comment]
Hi, it looks like windows is passing three separate names instead of collating them as a single argument.. 

ie it looking up 3 names:
- richmond
- victoria
- australia

instead of one name "richmond, victoria, australia"

I don't have a window box lying around to try it on, but a bit of research looking like you should put double quotes around the name instead of single quotes.

try this:

python optiburb.py --simplify-gpx --prune --debug=debug "richmond, victoria, australia"

Good luck with Richmond btw - that's a long ride.
